package com.submeter.entity;

import com.submeter.entity.enums.InvoiceStatus;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * A billing invoice for one subscription period.
 *
 * <p>Idempotency contract: The DB UNIQUE constraint on {@code (subscription_id, period_start)}
 * (V1 migration) ensures the nightly billing job can safely re-run after a crash without
 * creating duplicate invoices. No app-layer lock is needed.
 *
 * <p>Invoice number format: {@code INV-{YEAR}-{SEQ:04d}}, org-scoped.
 * Generated by the {@code next_invoice_number()} DB function (V3 migration).
 * The service layer calls this function at invoice creation time.
 *
 * <p>All monetary amounts are in paisa (INR cents). Display conversion (paisa → ₹)
 * happens at the API response layer, never in the billing engine.
 *
 * <p>FLAG: {@code dueAt} NOT NULL — required for the past-due scanner query
 * ({@code idx_invoices_status_due} index).
 * FLAG: {@code totalCents} NOT NULL DEFAULT 0 — a null total would produce a
 * ₹0 Razorpay order without error.
 */
@Entity
@Table(name = "invoices")
@NoArgsConstructor
@AllArgsConstructor
public class Invoice extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "org_id", nullable = false, updatable = false)
    private Organization organization;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "subscription_id", nullable = false, updatable = false)
    private Subscription subscription;

    /**
     * Human-readable identifier shown on PDF and in the UI.
     * Set once on creation via {@code next_invoice_number()}; immutable.
     */
    @Column(name = "invoice_number", nullable = false, unique = true, updatable = false)
    private String invoiceNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private InvoiceStatus status = InvoiceStatus.DRAFT;

    /** Start of the billed period (inclusive). Matches {@code subscription.currentPeriodStart}. */
    @Column(name = "period_start", nullable = false, updatable = false)
    private Instant periodStart;

    /** End of the billed period (exclusive). Matches {@code subscription.currentPeriodEnd}. */
    @Column(name = "period_end", nullable = false, updatable = false)
    private Instant periodEnd;

    /** Sum of all line item amounts, in paisa. Excludes tax. */
    @Column(name = "subtotal_cents", nullable = false)
    private long subtotalCents = 0L;

    /**
     * Tax amount in paisa. Always 0 in v1 (column reserved for GST integration).
     * FLAG: NOT NULL — a null tax amount would require null-safe addition everywhere.
     */
    @Column(name = "tax_cents", nullable = false)
    private long taxCents = 0L;

    /** subtotalCents + taxCents. Denormalized for Razorpay order creation. */
    @Column(name = "total_cents", nullable = false)
    private long totalCents = 0L;

    /** Payment due date. 7 days from OPEN transition (configurable via {@code app.billing.payment-due-days}). */
    @Column(name = "due_at", nullable = false)
    private Instant dueAt;

    /** Set when Razorpay fires {@code payment.captured} and the payment row is marked SUCCESS. */
    @Column(name = "paid_at")
    private Instant paidAt;

    /** Set when POST /invoices/:id/pay creates the Razorpay order. */
    @Column(name = "razorpay_order_id")
    private String razorpayOrderId;

    /**
     * Relative path within the storage root (e.g. {@code "invoices/INV-2025-0001.pdf"}).
     * Null until the PDF has been generated. The PDF is generated asynchronously (M5).
     */
    @Column(name = "pdf_path")
    private String pdfPath;

    /**
     * Line items generated by the billing engine.
     * CascadeType.ALL + orphanRemoval: the billing engine builds all line items
     * in one pass and replaces them as a unit if the draft is recalculated.
     */
    @OneToMany(
            mappedBy = "invoice",
            fetch = FetchType.LAZY,
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<InvoiceLineItem> lineItems = new ArrayList<>();

    @OneToMany(mappedBy = "invoice", fetch = FetchType.LAZY)
    private List<Payment> payments = new ArrayList<>();

    // Getters and Setters
    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public Subscription getSubscription() {
        return subscription;
    }

    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public InvoiceStatus getStatus() {
        return status;
    }

    public void setStatus(InvoiceStatus status) {
        this.status = status;
    }

    public Instant getPeriodStart() {
        return periodStart;
    }

    public void setPeriodStart(Instant periodStart) {
        this.periodStart = periodStart;
    }

    public Instant getPeriodEnd() {
        return periodEnd;
    }

    public void setPeriodEnd(Instant periodEnd) {
        this.periodEnd = periodEnd;
    }

    public long getSubtotalCents() {
        return subtotalCents;
    }

    public void setSubtotalCents(long subtotalCents) {
        this.subtotalCents = subtotalCents;
    }

    public long getTaxCents() {
        return taxCents;
    }

    public void setTaxCents(long taxCents) {
        this.taxCents = taxCents;
    }

    public long getTotalCents() {
        return totalCents;
    }

    public void setTotalCents(long totalCents) {
        this.totalCents = totalCents;
    }

    public Instant getDueAt() {
        return dueAt;
    }

    public void setDueAt(Instant dueAt) {
        this.dueAt = dueAt;
    }

    public Instant getPaidAt() {
        return paidAt;
    }

    public void setPaidAt(Instant paidAt) {
        this.paidAt = paidAt;
    }

    public String getRazorpayOrderId() {
        return razorpayOrderId;
    }

    public void setRazorpayOrderId(String razorpayOrderId) {
        this.razorpayOrderId = razorpayOrderId;
    }

    public String getPdfPath() {
        return pdfPath;
    }

    public void setPdfPath(String pdfPath) {
        this.pdfPath = pdfPath;
    }

    public List<InvoiceLineItem> getLineItems() {
        return lineItems;
    }

    public void setLineItems(List<InvoiceLineItem> lineItems) {
        this.lineItems = lineItems;
    }

    public List<Payment> getPayments() {
        return payments;
    }

    public void setPayments(List<Payment> payments) {
        this.payments = payments;
    }

    // Builder
    public static InvoiceBuilder builder() {
        return new InvoiceBuilder();
    }

    public static class InvoiceBuilder {
        private Organization organization;
        private Subscription subscription;
        private String invoiceNumber;
        private InvoiceStatus status = InvoiceStatus.DRAFT;
        private Instant periodStart;
        private Instant periodEnd;
        private long subtotalCents = 0L;
        private long taxCents = 0L;
        private long totalCents = 0L;
        private Instant dueAt;
        private Instant paidAt;
        private String razorpayOrderId;
        private String pdfPath;
        private List<InvoiceLineItem> lineItems = new ArrayList<>();
        private List<Payment> payments = new ArrayList<>();

        public InvoiceBuilder organization(Organization organization) {
            this.organization = organization;
            return this;
        }

        public InvoiceBuilder subscription(Subscription subscription) {
            this.subscription = subscription;
            return this;
        }

        public InvoiceBuilder invoiceNumber(String invoiceNumber) {
            this.invoiceNumber = invoiceNumber;
            return this;
        }

        public InvoiceBuilder status(InvoiceStatus status) {
            this.status = status;
            return this;
        }

        public InvoiceBuilder periodStart(Instant periodStart) {
            this.periodStart = periodStart;
            return this;
        }

        public InvoiceBuilder periodEnd(Instant periodEnd) {
            this.periodEnd = periodEnd;
            return this;
        }

        public InvoiceBuilder subtotalCents(long subtotalCents) {
            this.subtotalCents = subtotalCents;
            return this;
        }

        public InvoiceBuilder taxCents(long taxCents) {
            this.taxCents = taxCents;
            return this;
        }

        public InvoiceBuilder totalCents(long totalCents) {
            this.totalCents = totalCents;
            return this;
        }

        public InvoiceBuilder dueAt(Instant dueAt) {
            this.dueAt = dueAt;
            return this;
        }

        public InvoiceBuilder paidAt(Instant paidAt) {
            this.paidAt = paidAt;
            return this;
        }

        public InvoiceBuilder razorpayOrderId(String razorpayOrderId) {
            this.razorpayOrderId = razorpayOrderId;
            return this;
        }

        public InvoiceBuilder pdfPath(String pdfPath) {
            this.pdfPath = pdfPath;
            return this;
        }

        public InvoiceBuilder lineItems(List<InvoiceLineItem> lineItems) {
            this.lineItems = lineItems;
            return this;
        }

        public InvoiceBuilder payments(List<Payment> payments) {
            this.payments = payments;
            return this;
        }

        public Invoice build() {
            Invoice invoice = new Invoice();
            invoice.setOrganization(organization);
            invoice.setSubscription(subscription);
            invoice.setInvoiceNumber(invoiceNumber);
            invoice.setStatus(status);
            invoice.setPeriodStart(periodStart);
            invoice.setPeriodEnd(periodEnd);
            invoice.setSubtotalCents(subtotalCents);
            invoice.setTaxCents(taxCents);
            invoice.setTotalCents(totalCents);
            invoice.setDueAt(dueAt);
            invoice.setPaidAt(paidAt);
            invoice.setRazorpayOrderId(razorpayOrderId);
            invoice.setPdfPath(pdfPath);
            invoice.setLineItems(lineItems);
            invoice.setPayments(payments);
            return invoice;
        }
    }
}
