package com.submeter.entity;

import com.submeter.entity.enums.PricingModel;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.util.Map;

/**
 * One line in an invoice, generated by the billing engine.
 *
 * <p>Line items are append-only (created once, never updated).
 * The {@code amount} field is denormalized ({@code quantity * unitAmount}) so the
 * PDF renderer does not need to re-compute it and the audit trail is self-contained.
 *
 * <p>{@code tierDetail} stores the full per-tier breakdown for TIERED/METERED plans,
 * e.g.:
 * <pre>
 * {
 *   "tiers": [
 *     {"from": 1, "to": 1000, "units": 1000, "unitAmount": 50, "amount": 50000},
 *     {"from": 1001, "to": null, "units": 200, "unitAmount": 30, "amount": 6000}
 *   ]
 * }
 * </pre>
 * This is stored even if the plan tiers change later (version immutability).
 * Null for FLAT plan line items (no tier breakdown needed).
 *
 * <p>FLAG: {@code amount} NOT NULL — null would silently produce ₹0 invoice totals.
 * FLAG: {@code quantity > 0} CHECK in V1 migration prevents zero-quantity line items.
 */
@Entity
@Table(name = "invoice_line_items")
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceLineItem extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "invoice_id", nullable = false, updatable = false)
    private Invoice invoice;

    /** Human-readable description shown on PDF, e.g. "Pro Plan — June 2025" or "API Calls (1,200 units)". */
    @Column(name = "description", nullable = false, updatable = false)
    private String description;

    @Column(name = "quantity", nullable = false, updatable = false)
    private long quantity = 1L;

    /** Price per unit in paisa. For FLAT plans this is the total; quantity = 1. */
    @Column(name = "unit_amount", nullable = false, updatable = false)
    private long unitAmount;

    /** Denormalized: {@code quantity * unitAmount}. In paisa. */
    @Column(name = "amount", nullable = false, updatable = false)
    private long amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "pricing_model", nullable = false, length = 10, updatable = false)
    private PricingModel pricingModel;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "tier_detail", columnDefinition = "jsonb")
    private Map<String, Object> tierDetail;

    // Getters and Setters
    public Invoice getInvoice() {
        return invoice;
    }

    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getQuantity() {
        return quantity;
    }

    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    public long getUnitAmount() {
        return unitAmount;
    }

    public void setUnitAmount(long unitAmount) {
        this.unitAmount = unitAmount;
    }

    public long getAmount() {
        return amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

    public PricingModel getPricingModel() {
        return pricingModel;
    }

    public void setPricingModel(PricingModel pricingModel) {
        this.pricingModel = pricingModel;
    }

    public Map<String, Object> getTierDetail() {
        return tierDetail;
    }

    public void setTierDetail(Map<String, Object> tierDetail) {
        this.tierDetail = tierDetail;
    }

    // Builder
    public static InvoiceLineItemBuilder builder() {
        return new InvoiceLineItemBuilder();
    }

    public static class InvoiceLineItemBuilder {
        private Invoice invoice;
        private String description;
        private long quantity = 1L;
        private long unitAmount;
        private long amount;
        private PricingModel pricingModel;
        private Map<String, Object> tierDetail;

        public InvoiceLineItemBuilder invoice(Invoice invoice) {
            this.invoice = invoice;
            return this;
        }

        public InvoiceLineItemBuilder description(String description) {
            this.description = description;
            return this;
        }

        public InvoiceLineItemBuilder quantity(long quantity) {
            this.quantity = quantity;
            return this;
        }

        public InvoiceLineItemBuilder unitAmount(long unitAmount) {
            this.unitAmount = unitAmount;
            return this;
        }

        public InvoiceLineItemBuilder amount(long amount) {
            this.amount = amount;
            return this;
        }

        public InvoiceLineItemBuilder pricingModel(PricingModel pricingModel) {
            this.pricingModel = pricingModel;
            return this;
        }

        public InvoiceLineItemBuilder tierDetail(Map<String, Object> tierDetail) {
            this.tierDetail = tierDetail;
            return this;
        }

        public InvoiceLineItem build() {
            InvoiceLineItem item = new InvoiceLineItem();
            item.setInvoice(invoice);
            item.setDescription(description);
            item.setQuantity(quantity);
            item.setUnitAmount(unitAmount);
            item.setAmount(amount);
            item.setPricingModel(pricingModel);
            item.setTierDetail(tierDetail);
            return item;
        }
    }
}
