"use client";

import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { apiFetch, formatDate } from "@/lib/api";
import { StatusBadge } from "@/components/ui/status-dot";
import { toast } from "@/components/ui/toast";
import { Download, CreditCard, ChevronLeft, ChevronRight, AlertCircle } from "lucide-react";

interface Invoice {
  id: string;
  invoiceNumber: string;
  customerName: string;
  periodStart: string;
  periodEnd: string;
  totalCents: number;
  status: "DRAFT" | "OPEN" | "PAID" | "VOID" | "UNCOLLECTIBLE";
  dueAt: string;
  paidAt: string | null;
}

function formatINR(cents: number) {
  const code = typeof window !== "undefined" ? localStorage.getItem("currency_code") || "INR" : "INR";
  const val = (cents / 100);
  switch (code) {
    case "USD": return "$" + val.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    case "EUR": return "€" + val.toLocaleString("en-DE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    case "GBP": return "£" + val.toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    default: return "₹" + val.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
}

export default function InvoicesPage() {
  const { data: session } = useSession();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [cursor, setCursor] = useState<string | null>(null);
  const [hasNext, setHasNext] = useState(false);
  const [cursorStack, setCursorStack] = useState<string[]>([]);

  const load = async (cur: string | null = null) => {
    if (!session) return;
    setLoading(true); setError(null);
    try {
      const params = new URLSearchParams({ limit: "25" });
      if (cur) params.set("cursor", cur);
      const res = await apiFetch<{ content: Invoice[]; nextCursor: string | null; hasNext: boolean }>(
        `/invoices?${params}`, session
      );
      setInvoices(res.content);
      setCursor(res.nextCursor);
      setHasNext(res.hasNext);
    } catch (e: any) {
      setError(e.message ?? "Failed to load invoices");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [session]);

  const handlePdf = async (inv: Invoice) => {
    if (!session) return;
    try {
      const res = await fetch(`/api/invoices/${inv.id}/pdf`, {
        headers: { Authorization: `Bearer ${(session as any).accessToken}` },
      });
      if (!res.ok) throw new Error("PDF generation failed");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `${inv.invoiceNumber}.pdf`; a.click();
      URL.revokeObjectURL(url);
    } catch (e: any) { toast.error(e.message ?? "PDF failed"); }
  };

  return (
    <div style={{ maxWidth: 1100 }}>
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 20, fontWeight: 500, letterSpacing: "-0.02em", color: "var(--neutral-50)" }}>
          Invoices
        </h1>
        <p style={{ fontSize: 13, color: "var(--neutral-500)", marginTop: 3 }}>
          Generated by the nightly billing engine
        </p>
      </div>

      {error && (
        <div style={{
          display: "flex", alignItems: "center", gap: 8,
          padding: "10px 14px", marginBottom: 16,
          background: "var(--red-soft)", border: "1px solid var(--red-ring)",
          borderRadius: 7, fontSize: 13, color: "var(--red)",
        }}>
          <AlertCircle style={{ width: 14, height: 14 }} />
          {error}
          <button onClick={() => load()} style={{ marginLeft: "auto", fontSize: 12, background: "none", border: "1px solid currentColor", borderRadius: 4, padding: "2px 8px", color: "inherit", cursor: "pointer" }}>
            Retry
          </button>
        </div>
      )}

      <div style={{
        background: "var(--neutral-900)",
        border: "1px solid var(--neutral-800)",
        borderRadius: 8, overflow: "hidden",
        marginBottom: 14,
      }}>
        <table className="data-table">
          <thead>
            <tr>
              <th>Invoice</th>
              <th>Customer</th>
              <th>Period</th>
              <th style={{ textAlign: "right" }}>Amount</th>
              <th style={{ textAlign: "right" }}>Due</th>
              <th style={{ textAlign: "right" }}>Status</th>
              <th style={{ textAlign: "right", width: 120 }} />
            </tr>
          </thead>
          <tbody>
            {loading && Array.from({ length: 6 }, (_, i) => (
              <tr key={i}>
                {[70, 140, 80, 70, 80, 50, 100].map((w, j) => (
                  <td key={j} style={{ textAlign: j >= 3 ? "right" : "left" }}>
                    <div className="skeleton" style={{ height: 12, width: w, borderRadius: 3, marginLeft: j >= 3 ? "auto" : 0 }} />
                  </td>
                ))}
              </tr>
            ))}

            {!loading && invoices.length === 0 && (
              <tr>
                <td colSpan={7} style={{ textAlign: "center", padding: "60px 24px", color: "var(--neutral-600)", fontSize: 13 }}>
                  No invoices yet. The nightly billing engine generates them automatically.
                </td>
              </tr>
            )}

            <AnimatePresence mode="popLayout" initial={false}>
              {!loading && invoices.map((inv, i) => {
                const isPastDue = inv.status === "OPEN" && new Date(inv.dueAt).getTime() < Date.now();
                // Cap stagger at 15 rows; beyond that appear instantly
                const staggerDelay = i < 15 ? i * 0.025 : 0;

                return (
                  <motion.tr
                    key={inv.id}
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    transition={{ delay: staggerDelay, duration: 0.22, ease: [0.16, 1, 0.3, 1] }}
                    style={{
                      borderLeft: isPastDue ? "2px solid var(--amber)" : "2px solid transparent",
                    }}
                  >
                    <td>
                      <Link href={`/dashboard/invoices/${inv.id}`} style={{
                        fontFamily: "var(--font-mono)", fontSize: 12,
                        color: "var(--neutral-300)", textDecoration: "none",
                        transition: "color 150ms ease",
                      }}
                        onMouseEnter={e => (e.currentTarget.style.color = "var(--neutral-50)")}
                        onMouseLeave={e => (e.currentTarget.style.color = "var(--neutral-300)")}
                      >
                        {inv.invoiceNumber}
                      </Link>
                    </td>
                    <td style={{ color: "var(--neutral-200)", fontWeight: 450 }}>{inv.customerName}</td>
                    <td style={{ fontSize: 12, color: "var(--neutral-500)" }}>
                      {formatDate(inv.periodStart)}
                    </td>
                    <td style={{ textAlign: "right", fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--neutral-200)" }}>
                      {formatINR(inv.totalCents)}
                    </td>
                    <td style={{ textAlign: "right", fontFamily: "var(--font-mono)", fontSize: 12, color: isPastDue ? "var(--amber)" : "var(--neutral-500)" }}>
                      {formatDate(inv.dueAt)}
                    </td>
                    <td style={{ textAlign: "right" }}>
                      <StatusBadge status={inv.status} />
                    </td>
                    <td style={{ textAlign: "right" }}>
                      <div style={{ display: "flex", gap: 6, justifyContent: "flex-end" }}>
                        <button
                          onClick={() => handlePdf(inv)}
                          className="btn btn-ghost btn-sm"
                          style={{ fontSize: 11, display: "inline-flex", alignItems: "center", gap: 4 }}
                          title={`Download PDF for ${inv.invoiceNumber}`}
                        >
                          <Download style={{ width: 11, height: 11 }} />
                          PDF
                        </button>

                        {inv.status === "OPEN" && (
                          <Link
                            href={`/dashboard/invoices/${inv.id}`}
                            className="btn btn-sm"
                            style={{
                              background: "var(--neutral-200)",
                              color: "var(--neutral-950)",
                              border: "none",
                              fontSize: 11,
                              display: "inline-flex", alignItems: "center", gap: 4,
                              textDecoration: "none"
                            }}
                            onMouseEnter={e => (e.currentTarget.style.background = "white")}
                            onMouseLeave={e => (e.currentTarget.style.background = "var(--neutral-200)")}
                          >
                            <CreditCard style={{ width: 11, height: 11 }} />
                            Pay
                          </Link>
                        )}
                      </div>
                    </td>
                  </motion.tr>
                );
              })}
            </AnimatePresence>
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {!loading && (cursorStack.length > 0 || hasNext) && (
        <div style={{ display: "flex", gap: 6, justifyContent: "flex-end" }}>
          <button
            className="btn btn-secondary btn-sm"
            onClick={() => {
              const prev = cursorStack.slice(-1)[0] ?? null;
              setCursorStack(s => s.slice(0, -1));
              load(prev);
            }}
            disabled={cursorStack.length === 0}
          >
            <ChevronLeft style={{ width: 13, height: 13 }} /> Prev
          </button>
          <button
            className="btn btn-secondary btn-sm"
            onClick={() => {
              if (!cursor) return;
              setCursorStack(s => [...s, cursor]);
              load(cursor);
            }}
            disabled={!hasNext}
          >
            Next <ChevronRight style={{ width: 13, height: 13 }} />
          </button>
        </div>
      )}
    </div>
  );
}
